import { ForensicState } from '../types/forensics';

/**
 * Generates an Executive Security Audit & Forensics Report in Markdown format.
 */
export function generateMarkdownReport(state: ForensicState): string {
  const repoName = state.metadata?.fullName || 'Target Repository';
  const analyzedDate = state.metadata?.analyzedAt || new Date().toISOString();
  const criticalSecrets = state.secrets.filter((s) => s.severity === 'critical');
  const criticalVulns = state.vulnerabilities.filter((v) => v.severity === 'critical');

  return `# Executive Forensic Audit Report: ${repoName}

**Generated by**: repo-forensics (Client-Side Forensic Engine)  
**Date of Audit**: ${analyzedDate}  
**Overall Security Posture Score**: ${state.securityScore} / 100 (${state.securityScore < 50 ? 'CRITICAL RISK' : state.securityScore < 80 ? 'ATTENTION REQUIRED' : 'ACCEPTABLE POSTURE'})  
**Engine Baseline**: 100% Client-Side • Zero Telemetry  

---

## 1. Executive Summary
During the static forensic analysis of \`${repoName}\`, a total of **${state.secrets.length} hardcoded secrets/credentials** and **${state.vulnerabilities.length} software vulnerabilities** were identified. 

- **Critical Compromises**: ${criticalSecrets.length} high-entropy active credentials.
- **Supply Chain Vulnerabilities**: ${state.dependencies.filter((d) => d.vulnerabilities.length > 0).length} dependencies with known CVEs.
- **Commit Anomalies**: ${state.commits.filter((c) => c.isAfterHours || c.isPotentialSpoof).length} suspicious commit interactions (after-hours or unverified authorship).

---

## 2. Hardcoded Credentials & Entropy Breakdown
${
  state.secrets.length === 0
    ? '_No hardcoded secrets detected based on current Shannon threshold._\n'
    : state.secrets
        .map(
          (s) =>
            `### [${s.severity.toUpperCase()}] ${s.category}
- **Location**: \`${s.file}:${s.line}\`
- **Masked Token**: \`${s.maskedString}\`
- **Shannon Entropy**: **${s.entropy}**
- **Description**: ${s.description}
`
        )
        .join('\n')
}

---

## 3. Vulnerability & CVE Supply Chain Findings
${
  state.vulnerabilities.length === 0
    ? '_No software vulnerabilities recorded in this session._\n'
    : state.vulnerabilities
        .map(
          (v) =>
            `### ${v.cve || 'Vulnerability'}: ${v.title}
- **Severity**: ${v.severity.toUpperCase()}
- **Target**: \`${v.package || v.location}\`
- **Installed**: \`${v.installedVersion || 'N/A'}\` | **Patched**: \`${v.patchedVersion || 'N/A'}\`
- **Impact**: ${v.description}
- **Remediation**: ${v.recommendation}
`
        )
        .join('\n')
}

---

## 4. Git Timeline & Forensic Commit Anomalies
${
  state.commits.length === 0
    ? '_No commit history analyzed._\n'
    : state.commits
        .map(
          (c) =>
            `- **Commit \`${c.shortSha}\`** by **${c.author}** (\`${c.email}\`) on ${c.date}
  - Message: *"${c.message}"*
  - Anomalies: ${
    [
      c.isAfterHours ? '⚠️ After-Hours Activity' : null,
      c.isPotentialSpoof ? '🚨 Potential Author Spoofing' : null,
      c.suspiciousKeywordsDetected.length > 0
        ? `Keywords: ${c.suspiciousKeywordsDetected.join(', ')}`
        : null,
    ]
      .filter(Boolean)
      .join(' | ') || 'None detected'
  }
`
        )
        .join('\n')
}

---

## 5. Immediate Remediation Action Plan
1. **Revoke and Rotate Leaked Secrets**: Immediately revoke all AWS keys, GitHub PATs, and database credentials detected above.
2. **Patch Direct Dependencies**: Upgrade vulnerable packages (${state.dependencies
    .filter((d) => d.vulnerabilities.length > 0)
    .map((d) => d.name)
    .join(', ') || 'N/A'}) to their latest patched releases.
3. **Audit High-Churn & Spoofed Commits**: Conduct peer review on commits authored by unverified email relays.
4. **Harden Attack Surface**: Remove cleartext passwords and configure database ingress firewalls.

---
*Report certified by repo-forensics • Todos os direitos reservados © 2026*
`;
}

/**
 * Generates standalone, print-optimized HTML document for instant printing or PDF saving.
 */
export function generatePrintableHtml(title: string, markdownContent: string): string {
  // Convert simple markdown headings and lists to HTML
  const escapeHtml = (text: string) =>
    text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

  const lines = markdownContent.split('\n');
  const htmlParts: string[] = [];

  for (const line of lines) {
    if (line.startsWith('# ')) {
      htmlParts.push(`<h1>${escapeHtml(line.slice(2))}</h1>`);
    } else if (line.startsWith('## ')) {
      htmlParts.push(`<h2>${escapeHtml(line.slice(3))}</h2>`);
    } else if (line.startsWith('### ')) {
      htmlParts.push(`<h3>${escapeHtml(line.slice(4))}</h3>`);
    } else if (line.startsWith('- ')) {
      htmlParts.push(`<li>${escapeHtml(line.slice(2))}</li>`);
    } else if (line.trim() === '---') {
      htmlParts.push('<hr />');
    } else if (line.trim().length > 0) {
      htmlParts.push(`<p>${escapeHtml(line)}</p>`);
    }
  }

  const bodyHtml = htmlParts.join('\n');

  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    @page {
      size: A4;
      margin: 18mm 15mm;
    }
    * {
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #09090b;
      background: #ffffff;
      line-height: 1.5;
      font-size: 11pt;
      margin: 0;
      padding: 24px;
    }
    h1 {
      font-size: 18pt;
      color: #0e7490;
      border-bottom: 2px solid #0e7490;
      padding-bottom: 6px;
      margin-top: 0;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }
    h2 {
      font-size: 13pt;
      color: #18181b;
      margin-top: 20px;
      margin-bottom: 8px;
      border-bottom: 1px solid #e4e4e7;
      padding-bottom: 4px;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }
    h3 {
      font-size: 11pt;
      color: #27272a;
      margin-top: 14px;
      margin-bottom: 4px;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }
    p {
      margin: 4px 0 8px;
    }
    li {
      margin-left: 20px;
      margin-bottom: 4px;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      font-size: 10pt;
    }
    hr {
      border: none;
      border-top: 1px dashed #d4d4d8;
      margin: 16px 0;
    }
    .print-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      font-size: 9pt;
      color: #71717a;
      border-bottom: 1px solid #e4e4e7;
      padding-bottom: 6px;
    }
    .print-footer {
      margin-top: 32px;
      border-top: 1px solid #e4e4e7;
      padding-top: 8px;
      font-size: 9pt;
      color: #71717a;
      text-align: center;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    }
    @media print {
      body {
        padding: 0;
      }
    }
  </style>
  <script>
    window.onload = function() {
      try {
        window.print();
      } catch (e) {
        console.warn('Auto-print blocked', e);
      }
    };
  </script>
</head>
<body>
  <div class="print-header">
    <span>repo-forensics • Auditoria de Segurança Forense</span>
    <span>Emissão: ${new Date().toLocaleDateString('pt-BR')} ${new Date().toLocaleTimeString('pt-BR')}</span>
  </div>
  ${bodyHtml}
  <div class="print-footer">
    repo-forensics • Todos os direitos reservados © 2026 • 100% Client-Side
  </div>
</body>
</html>`;
}

/**
 * Serializes the complete audit state to a JSON session string.
 */
export function exportSessionToJson(state: ForensicState): string {
  const exportPayload = {
    version: '1.0.0',
    exportedAt: new Date().toISOString(),
    generator: 'repo-forensics',
    data: state,
  };
  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Validates and imports a JSON session string back into ForensicState.
 */
export function importSessionFromJson(jsonString: string): ForensicState {
  try {
    const parsed = JSON.parse(jsonString);
    const data = parsed.data || parsed;

    if (!data || typeof data !== 'object') {
      throw new Error('Invalid JSON format: missing root forensic data object');
    }

    // Defensive check of core arrays
    return {
      metadata: data.metadata || null,
      secrets: Array.isArray(data.secrets) ? data.secrets : [],
      vulnerabilities: Array.isArray(data.vulnerabilities) ? data.vulnerabilities : [],
      dependencies: Array.isArray(data.dependencies) ? data.dependencies : [],
      commits: Array.isArray(data.commits) ? data.commits : [],
      architectureNodes: Array.isArray(data.architectureNodes) ? data.architectureNodes : [],
      anomalies: Array.isArray(data.anomalies) ? data.anomalies : [],
      securityScore: typeof data.securityScore === 'number' ? data.securityScore : 0,
      shannonThreshold: typeof data.shannonThreshold === 'number' ? data.shannonThreshold : 3.5,
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown parsing error';
    throw new Error(`Failed to import forensic audit session: ${msg}`);
  }
}

/**
 * Triggers native browser download for text/json/markdown content.
 */
export function downloadFile(filename: string, content: string, mimeType: string): void {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copies string to clipboard with fallback.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    // Fallback for older browsers / iframe restrictions
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch {
    return false;
  }
}
